name: run-store-secrets
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Secret
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
          echo "$super_secret" 